### ISSUE TITLE
Improve guide structure

### ISSUE THREAD

**Issue by anajsana** [todogroup/outbound-oss#18]
@cornelius @misappi  I have proposed a different structure idea to have a clear and homogeneous path to follow when reading this guide. Feel free to review the PR https://github.com/Open-Source-Compliance/outbound-oss/pull/17

**Comment by anajsana** [comment]
@cornelius @misappi I've been working on some of the sections we had to cover using the new structure: https://github.com/Open-Source-Compliance/outbound-oss/pull/27

**Comment by misappi** [comment]
Structure is OK now. Closing this issue.
