### ISSUE TITLE
Spare time contributions

### ISSUE THREAD

**Issue by OliverFendt** [todogroup/outbound-oss#2]
We need to describe whether there is something to do if an employee wants to contribute to an OSS project during his spare time.

**Comment by OliverFendt** [comment]
I have created a branch - working on that
https://github.com/Open-Source-Compliance/outbound-oss/tree/spare-time-contributions

**Comment by cornelius** [comment]
An interesting approach to this is GitHub's balanced employee IP agreement: https://github.com/github/balanced-employee-ip-agreement

**Comment by misappi** [comment]
PR #44 was merged. Thus, this issue can be closed.
