### ISSUE TITLE
Guidance for OSPOs how to convince the developers about the necessity of governance

### ISSUE THREAD

**Issue by mkurzman** [todogroup/outbound-oss#29]
Today the idea came up when discussing the "Why do we need this?" section might already be known to the target group of this guide. But what would be helpful would be a guide on how to convince the developers and raise their awareness.
E.g. collection about good practices what helped and what could be good "developer facing" material.

**Comment by anajsana** [comment]
Thanks for sharing this idea @mkurzman ! I think this topic can be a dedicated TODO guide. we might want to also show the top-down level approach (how to convince the high-level managers to build an OSPO). 

If this sounds good to you, could you please provide a title and abstract idea, with desired topics to talk about in this issue? [Tracking ideas for TODO guides for 2022](https://github.com/todogroup/todogroup.org/issues/143) 

Thanks 😊

**Comment by misappi** [comment]
Need to discuss with Marcel what is really meant by this. Governance as a topic can be very broad and should be an own guide as @anajsana already suggested. If it is specifically about governance for contributions to open source projects, we could address that with a few sentences in this guide, of course.

**Comment by misappi** [comment]
TBD: Is this something we should put into our guideline or is this something that should be contained in company-internal material?

Not required for v1.0 of this guideline.

**Comment by anajsana** [comment]
> Not required for v1.0 of this guideline.

I'd say to stick to that and close this issue. Once v1.0 is published, we can re-open it anytime 👍
