### ISSUE TITLE
CLA handling in an organization

### ISSUE THREAD

**Issue by OliverFendt** [todogroup/outbound-oss#3]
We need to describe a good practice how to handle CLAs which are required by OSS projects an employee wants to contribute to.

**Comment by OliverFendt** [comment]
I started working on this and added a section about CLA/DCOs in contributing-to-existing-projects.md 

https://github.com/Open-Source-Compliance/outbound-oss/blob/rework-contr-to-existing/Contributions-to-existing-projects.md

**Comment by misappi** [comment]
To be checked if this is already contained in "starting an OSS project".

**Comment by misappi** [comment]
PR #32 was merged. Thus, this issue can be closed.
