### ISSUE TITLE
Section Abbreviations

### ISSUE THREAD

**Issue by OliverFendt** [todogroup/outbound-oss#51]
Shall we add a section with the used Abbreviations, the references chapter might be a good place

**Comment by OliverFendt** [comment]
So far I have identified the following abbreviations:

- API = Application Programming Interface
- CII = Core Infrastructure Initiative
- CLA = Contributor License Agreement
- CCLA = Corporate Contributor License Agreement
-  CHAOSS = Community Health Analytics Open Source Software 
- CNCF = Cloud Native Computing Foundation
- DCO = Developers Certificate of Origin
- ECC = Export Control and Customs
- ECCN = Export Control Classification Number
- GPL = GNU General Public License
- ICLA = Individual Contributor License Agreement
- IP = Intellectual Property
- JSON = Java Script Object Notation
- KPI = Key Performance Indicator
- LFX = Linux Foundation Collaboration Metrics
- MIT = Massachusetts Institute of Technology
- NPM = Node Package Manager
- OSI = Open Source Initiative
- OSPO Open Source Program Office
- PyPI = Python Package Index

Did anybody find additional abbreviations

**Comment by misappi** [comment]
PR #55 was merged. Thus, this issue can be closed.
