### ISSUE TITLE
Create releasing notes once the v 1.0 guide version goes live

### ISSUE THREAD

**Issue by anajsana** [todogroup/outbound-oss#57]
I think that an idea to (1) let people know about what the v 1.0 covers, (2) that this is an ongoing guide, and (3) that there will be a v.2.0 (and officially welcome them to contribute) could be a good thing to have 👍 https://github.com/todogroup/outbound-oss/releases/new

**Comment by misappi** [comment]
We will create a changelog file with the release notes, work on the text and then create a tag and copy the text over to the release notes.

**Comment by misappi** [comment]
I created a proposal for a CHANGELOG.md - see #71. The content could be used for the release note for v1.0.0

**Comment by misappi** [comment]
[First release](https://github.com/todogroup/outbound-oss/releases/tag/v1.0.0) created.
