### ISSUE TITLE
Clarify that decision responsibility may reach beyond development unit

### ISSUE THREAD

**Issue by gkunz** [todogroup/outbound-oss#63]
The guide states that the responsibility for deciding whether or not to contibnutye rests with the unit which funds the development (and own the corresponding products) [1]. I generally agree with that, but I think it would be useful for the guide to expand a bit on this and add a note that other stakeholders can/should be involved as well to ensure a higher level perspective on:

* company wide strategy: alignment across business areas to avoid that different units engage in contradicting actions. This is not exclusively an open source issue per se, but can be part of usual business and product strategy work - however - in the open contradicting action become more more apparent and potentially harmful.

* If patents and licensing is important (this differs very much across industries), then the IPR folks are stakeholders as well.

Later parts of the guide touch upon this, but it might be helpful to briefly reference this issue here as well.

This issue is based on a review of this PR https://github.com/todogroup/todogroup.org/pull/336

[1] https://github.com/todogroup/outbound-oss/blob/main/content/02-contributions-to-existing-projects.md#responsibility-decision-rests-with-unit

**Comment by OliverFendt** [comment]
@gkunz  thank you for the suggestion.

Legal and IP are per se to be involved in the approval process.

Regarding the other topic you brought up I agree that if possible there should be an alignement somehow in order to ensure that an open source contribution or an own open source project does not cannibalize the business of another unit.

I will think about how we can describe this and still keep it simple

**Comment by gkunz** [comment]
Hi @OliverFendt. Thank you for the feedback. Well, I guess we all want to keep the process as lightweight as possible and I also don't want the guide to state that each and everybody should in involved and agree to the contribution. Then you'd never get anything done.

In my company, the team which reviews and clears upstream contributions is expected to have a solid understanding of the larger business strategies across BAs and so, they can at least keep an eye on alignment with the company at large (and trigger more in-depth discussion if really needed). That's just how we do it, and probably the guide should just mention that contributions should fit into the overall company strategy.

**Comment by OliverFendt** [comment]
solved with PR #69
