### ISSUE TITLE
Explain the reasoning behind the major release model

### ISSUE THREAD

**Issue by gkunz** [todogroup/outbound-oss#64]
The guide describes the Major to major release release model contribution model. It would be great if the text could more explicitly explain the motivation for using releases as decision points for approvals. These decision points are typically not closely related to the actual properties checked, such as IP policy, CLA/DCO contents, i.e., those things do not typically change across releases.

So, is this idea behind tying re-approval to releases primarily to have some form of regular check build into the process, but not so much to ensure that changes of licenses etc. get caught in time?

This issue is based on a review of PR https://github.com/todogroup/todogroup.org/pull/336

**Comment by OliverFendt** [comment]
@gkunz thank you for your comment.

Indeed the idea behind the "major to major release model" is on the one hand side to off load the developers from repeatedly going through the approval process and on the other hand to keep a certain level of control. 

Furthermore license changes, if they happen are often done with a new major release (see OpenSSL for example) with this approach all stakeholders (legal, IP, ECC, etc.) are involved and can decide on whether the developer is still allowed to contribute or not.

Does this help? If so I will update the guide accordingly

**Comment by gkunz** [comment]
Hi @OliverFendt. Thank you for the explanation. I think this is fine and adding one or two sentences to the paragraph clarifies this also for a reader less familiar with the topic.

Thank you for addressing my issue.

**Comment by misappi** [comment]
From the discussion in our sync meeting:

- Please make clear that the approaches described in the text are just examples
- Please also make clear when (under which conditions) a specific approach makes sense - e.g., the relation to some internal processes

**Comment by OliverFendt** [comment]
solved with PR #69
