### ISSUE TITLE
Add changes from todogroup.org

### ISSUE THREAD

**Issue by misappi** [todogroup/outbound-oss#65]
Requested changes from the todogroup.org repo must be added to this repo.

Also the abbreviations (#61 ) and the personal pronouns (#62) should be done in this repo first.

**Comment by cornelius** [comment]
The pull request https://github.com/todogroup/outbound-oss/pull/66 incorporates the feedback from the todogroup.org repo.

**Comment by misappi** [comment]
#66 merged. We can close this issue.
